In [0]:
from tensorflow.keras.preprocessing.text import one_hot

In [0]:
import numpy as np
import pandas as pd

In [7]:
from google.colab import files
uploaded = files.upload()

Saving data_for_embeddings.txt to data_for_embeddings (2).txt

In [10]:
import io
df = pd.read_csv(io.BytesIO(uploaded['data_for_embeddings.txt']),error_bad_lines=False)

b'Skipping line 5: expected 1 fields, saw 6\nSkipping line 7: expected 1 fields, saw 11\nSkipping line 11: expected 1 fields, saw 2\nSkipping line 13: expected 1 fields, saw 4\nSkipping line 15: expected 1 fields, saw 6\nSkipping line 17: expected 1 fields, saw 9\nSkipping line 19: expected 1 fields, saw 9\nSkipping line 27: expected 1 fields, saw 5\nSkipping line 29: expected 1 fields, saw 2\nSkipping line 31: expected 1 fields, saw 13\nSkipping line 37: expected 1 fields, saw 6\nSkipping line 39: expected 1 fields, saw 8\nSkipping line 45: expected 1 fields, saw 3\nSkipping line 47: expected 1 fields, saw 11\nSkipping line 51: expected 1 fields, saw 2\nSkipping line 53: expected 1 fields, saw 3\nSkipping line 55: expected 1 fields, saw 16\nSkipping line 59: expected 1 fields, saw 2\nSkipping line 61: expected 1 fields, saw 4\nSkipping line 63: expected 1 fields, saw 11\nSkipping line 73: expected 1 fields, saw 11\nSkipping line 77: expected 1 fields, saw 2\nSkipping line 79: expected 1 fields, saw 5\nSkipping line 81: expected 1 fields, saw 2\nSkipping line 83: expected 1 fields, saw 4\nSkipping line 85: expected 1 fields, saw 14\nSkipping line 87: expected 1 fields, saw 9\nSkipping line 91: expected 1 fields, saw 3\nSkipping line 93: expected 1 fields, saw 8\nSkipping line 95: expected 1 fields, saw 7\nSkipping line 101: expected 1 fields, saw 6\nSkipping line 103: expected 1 fields, saw 5\nSkipping line 109: expected 1 fields, saw 17\nSkipping line 111: expected 1 fields, saw 2\nSkipping line 113: expected 1 fields, saw 2\nSkipping line 115: expected 1 fields, saw 2\nSkipping line 116: expected 1 fields, saw 2\nSkipping line 117: expected 1 fields, saw 3\n'

In [11]:
df

                     Dollar gains on Greenspan speech
0   The dollar has hit its highest level against t...
1                   Ad sales boost Time Warner profit
2   Rosneft officials were unavailable for comment...
3                   High fuel prices hit BA's profits
4   British Airways has blamed high fuel prices fo...
5                   Ask Jeeves tips online ad revival
6   Ask Jeeves has become the third leading online...
7                   Pernod takeover talk lifts Domecq
8   Shares in UK drinks and food firm Allied Domec...
9                    Japan narrowly escapes recession
10                     Peugeot deal boosts Mitsubishi
11                   Telegraph newspapers axe 90 jobs
12  The Daily and Sunday Telegraph newspapers are ...
13  The Telegraph Group says the cuts are needed t...
14  Pearson's Financial Times said last week it wa...
15                   Air passengers win new EU rights
16                    Parmalat boasts doubled profits
17                  India's rupee hits five-year high
18  India's rupee has hit a five-year high after S...
19                    India widens access to telecoms
20  India has raised the limit for foreign direct ...

In [20]:
pd.get_dummies(df)

    Dollar gains on Greenspan speech_Ad sales boost Time Warner profit  ...  Dollar gains on Greenspan speech_The dollar has hit its highest level against the euro in almost three months after the Federal Reserve head said the US trade deficit is set to stabilise.
0                                                   0                   ...                                                  1
1                                                   1                   ...                                                  0
2                                                   0                   ...                                                  0
3                                                   0                   ...                                                  0
4                                                   0                   ...                                                  0
5                                                   0                   ...                                                  0
6                                                   0                   ...                                                  0
7                                                   0                   ...                                                  0
8                                                   0                   ...                                                  0
9                                                   0                   ...                                                  0
10                                                  0                   ...                                                  0
11                                                  0                   ...                                                  0
12                                                  0                   ...                                                  0
13                                                  0                   ...                                                  0
14                                                  0                   ...                                                  0
15                                                  0                   ...                                                  0
16                                                  0                   ...                                                  0
17                                                  0                   ...                                                  0
18                                                  0                   ...                                                  0
19                                                  0                   ...                                                  0
20                                                  0                   ...                                                  0

[21 rows x 21 columns]

In [0]:
voc_size=1000000

In [24]:
onehot_repr=[one_hot(words,voc_size)for words in df] 
print(onehot_repr)

[[52827, 630024, 463537, 133684, 23145]]

In [0]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [27]:
df_length=10
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=df_length)
print(embedded_docs)

[[     0      0      0      0      0  52827 630024 463537 133684  23145]]

In [0]:
dim=25

In [0]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=df_length))
model.compile('adam','mse')

In [32]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
embedding (Embedding)        (None, 10, 10)            10000000
=================================================================
Total params: 10,000,000
Trainable params: 10,000,000
Non-trainable params: 0
_________________________________________________________________

In [33]:
print(model.predict(embedded_docs))

[[[ 0.03190674 -0.02905493 -0.03862699 -0.01211853  0.0233037
   -0.00829172 -0.03299068 -0.03928864  0.03969647  0.04134179]
  [ 0.03190674 -0.02905493 -0.03862699 -0.01211853  0.0233037
   -0.00829172 -0.03299068 -0.03928864  0.03969647  0.04134179]
  [ 0.03190674 -0.02905493 -0.03862699 -0.01211853  0.0233037
   -0.00829172 -0.03299068 -0.03928864  0.03969647  0.04134179]
  [ 0.03190674 -0.02905493 -0.03862699 -0.01211853  0.0233037
   -0.00829172 -0.03299068 -0.03928864  0.03969647  0.04134179]
  [ 0.03190674 -0.02905493 -0.03862699 -0.01211853  0.0233037
   -0.00829172 -0.03299068 -0.03928864  0.03969647  0.04134179]
  [ 0.01158872 -0.0266825   0.03854868 -0.01631695  0.02742555
    0.045941   -0.00435656 -0.016685   -0.0258296   0.01050718]
  [ 0.03635914 -0.01087023  0.04211241 -0.03207757  0.01430652
    0.01664758  0.03306692 -0.01736748  0.04135417  0.04844436]
  [ 0.04623237 -0.03474952 -0.02600836  0.04153385 -0.040167
   -0.03951211  0.04249636 -0.01429953  0.02652714 -0.04877741]
  [-0.02923951 -0.03720163 -0.03258913 -0.02771764 -0.04753522
   -0.02501011 -0.03727    -0.04311555  0.04241576 -0.0397099 ]
  [-0.00901611  0.03336575 -0.01791001  0.04889933  0.04220804
    0.02134025 -0.00700774 -0.04229208 -0.02720627  0.02282072]]]

In [34]:

embedded_docs[0]

array([     0,      0,      0,      0,      0,  52827, 630024, 463537,
       133684,  23145], dtype=int32)

In [35]:
print(model.predict(embedded_docs)[0])

[[ 0.03190674 -0.02905493 -0.03862699 -0.01211853  0.0233037  -0.00829172
  -0.03299068 -0.03928864  0.03969647  0.04134179]
 [ 0.03190674 -0.02905493 -0.03862699 -0.01211853  0.0233037  -0.00829172
  -0.03299068 -0.03928864  0.03969647  0.04134179]
 [ 0.03190674 -0.02905493 -0.03862699 -0.01211853  0.0233037  -0.00829172
  -0.03299068 -0.03928864  0.03969647  0.04134179]
 [ 0.03190674 -0.02905493 -0.03862699 -0.01211853  0.0233037  -0.00829172
  -0.03299068 -0.03928864  0.03969647  0.04134179]
 [ 0.03190674 -0.02905493 -0.03862699 -0.01211853  0.0233037  -0.00829172
  -0.03299068 -0.03928864  0.03969647  0.04134179]
 [ 0.01158872 -0.0266825   0.03854868 -0.01631695  0.02742555  0.045941
  -0.00435656 -0.016685   -0.0258296   0.01050718]
 [ 0.03635914 -0.01087023  0.04211241 -0.03207757  0.01430652  0.01664758
   0.03306692 -0.01736748  0.04135417  0.04844436]
 [ 0.04623237 -0.03474952 -0.02600836  0.04153385 -0.040167   -0.03951211
   0.04249636 -0.01429953  0.02652714 -0.04877741]
 [-0.02923951 -0.03720163 -0.03258913 -0.02771764 -0.04753522 -0.02501011
  -0.03727    -0.04311555  0.04241576 -0.0397099 ]
 [-0.00901611  0.03336575 -0.01791001  0.04889933  0.04220804  0.02134025
  -0.00700774 -0.04229208 -0.02720627  0.02282072]]